# -*- coding: utf-8 -*-
from lib2to3.fixer_util import find_binding

from Bio.SeqRecord import SeqRecord
from Bio import SeqIO
import networkx as nx
from typing import List, Tuple, Set

# FFC and BF imports
from AGICI_lab_S5_FFC import find_motifs as find_ffl
from AGICI_lab_S5 import find_motifs as fins_bf


def get_motifs_clusters(G: nx.DiGraph, motifs: list, mtype: str = "ffl") -> List[Set[str]]:
    """
    Analyse the subgraph created from edges belonging to motifs.

    Parameters
    ----------
    - param: G : Networkx digraph
        Graph to analyze
    - param: motifs : list
        List of motifs
    - param: mtype : str
        Motif type ("ffl" or "bf")
    - return : list
        List of weakly connected components in the motifs subgraph
    """
    connected_components = []
    # ------- IMPLEMENT HERE THE BODY OF THE FUNCTION ------- #
    
    if mtype == "ffl":
        for t in motifs:
            connected_components.append({t[0], t[1]})
            connected_components.append({t[0], t[2]})
            connected_components.append({t[1], t[2]})
    elif mtype == "bf":
        for t in motifs:
            connected_components.append({t[0], t[2]})
            connected_components.append({t[0], t[3]})
            connected_components.append({t[1], t[2]})
            connected_components.append({t[1], t[3]})
    else:
        raise ValueError
    
    # ----------------- END OF FUNCTION --------------------- #
    return connected_components


def compare_with_random_graphs(G: nx.DiGraph, n_random: int):
    """
    Compare motif statistics of the original graph with random graphs generated by the directed configuration model.
    For each motif type (ffl and bf), print:
        - Number of motifs
        - Number of nodes participating in motifs
        - Number of motif clusters
        - Distribution of motif cluster sizes
    Parameters
    ----------
    - param: G : Networkx digraph
        Original graph to analyze
    - param: n_random : int
        Number of random graphs to generate
    """
    # ------- IMPLEMENT HERE THE BODY OF THE FUNCTION ------- #





    # ----------------- END OF FUNCTION --------------------- #

if __name__ == "__main__":

    # ------- IMPLEMENT HERE THE MAIN FOR THIS SESSION ------- #
    import time
    start_time = time.time()

    G1=nx.read_graphml('Ecoli_TRN.graphml')
    G2=nx.read_graphml('Ecoli_operon_TRN.graphml')

    ...

    print("--- %s seconds ---" % (time.time() - start_time))
    # ------------------- END OF MAIN ------------------------ #

