# -*- coding: utf-8 -*-
from lib2to3.fixer_util import find_binding

from Bio.SeqRecord import SeqRecord
from Bio import SeqIO
import networkx as nx
from typing import List, Tuple, Set
<<<<<<< HEAD
from collections import Counter
import random
# FFC and BF imports
from AGICI_lab_S5_FFC import find_motifs_FFL
from AGICI_lab_S5 import find_motifs_BF
from AGICI_lab_S3 import degree_distribution, TF_RISet_parse 
=======

import random
from AGICI_lab_S3 import degree_distribution, TF_RISet_parse
from AGICI_lab_S5 import find_motifs_BF
from AGICI_lab_S5_FFC import find_motifs_FFL
from collections import Counter
>>>>>>> 89e5d90212fe481aeff7c65cc5192a34bc1166f2


def get_motifs_clusters(G: nx.DiGraph, motifs: list, mtype: str = "ffl") -> List[Set[str]]:

    """
    Analyse the subgraph created from edges belonging to motifs.

    Parameters
    ----------
    - param: G : Networkx digraph
        Graph to analyze
    - param: motifs : list
        List of motifs
    - param: mtype : str
        Motif type ("ffl" or "bf")
    - return : list
        List of weakly connected components in the motifs subgraph
    """
    connected_components = []
    # ------- IMPLEMENT HERE THE BODY OF THE FUNCTION ------- #
    if mtype == "ffl":
        for t in motifs:
            connected_components.append({t[0], t[1]})
            connected_components.append({t[0], t[2]})
            connected_components.append({t[1], t[2]})
    elif mtype == "bf":
        for t in motifs:
            connected_components.append({t[0], t[2]})
            connected_components.append({t[0], t[3]})
            connected_components.append({t[1], t[2]})
            connected_components.append({t[1], t[3]})
    else:
        raise ValueError
    
    return connected_components
    


def compare_with_random_graphs(G: nx.DiGraph, n_random: int):
    """
    Compare motif statistics of the original graph with random graphs generated by the directed configuration model.
    For each motif type (ffl and bf), print:
        - Number of motifs
        - Number of nodes participating in motifs
        - Number of motif clusters
        - Distribution of motif cluster sizes
    Parameters
    ----------
    - param: G : Networkx digraph
        Original graph to analyze
    - param: n_random : int
        Number of random graphs to generate
    """
    # ------- IMPLEMENT HERE THE BODY OF THE FUNCTION ------- #

    #----------Statistics OG -------------------------------- #
    in_degree_sequence, best = degree_distribution(G, 'in', 'ALL', 5)
    out_degree_sequence, best2 = degree_distribution(G, 'out', 'ALL', 5)
    list_in = list(in_degree_sequence.values())
    list_out = list(out_degree_sequence.values())
    motifs_FFL_og = find_motifs_FFL(G)
    motifs_BF_og = find_motifs_BF(G)
    nodes_in_motifs_BF_og = set()
    nodes_in_motifs_FFL_og = set()
    for BF in motifs_BF_og:
            for node in BF:
                nodes_in_motifs_BF_og.add(node)
    for FFL in motifs_FFL_og:
            for node in FFL:
                nodes_in_motifs_FFL_og.add(node)
    nodes_in_all_motifs_og = nodes_in_motifs_BF_og | nodes_in_motifs_FFL_og
    motif_clusters_BF_og = get_motifs_clusters(G, motifs_BF_og, 'bf')
    motif_clusters_FFL_og = get_motifs_clusters(G, motifs_FFL_og, 'ffl')
    number_of_cluster_FFL_og = len(motif_clusters_FFL_og)
    number_of_cluster_BF_og = len(motif_clusters_BF_og)
    cluster_distribution_FFL_og = Counter([len(x) for x in motif_clusters_FFL_og])
    cluster_distribution_BF_og = Counter([len(x) for x in motif_clusters_BF_og])
    for i in range(n_random):
        random_subgraph = nx.directed_configuration_model(list_in, list_out)

    # ---------Statistics Random -------------------------------------- #
        motifs_FFL = find_motifs_FFL(random_subgraph)
        motifs_BF = find_motifs_BF(random_subgraph)
        nodes_in_motifs_BF = set()
        nodes_in_motifs_FFL = set()
        for BF in motifs_BF:
            for node in BF:
                nodes_in_motifs_BF.add(node)
        for FFL in motifs_FFL:
            for node in FFL:
                nodes_in_motifs_FFL.add(node)
        nodes_in_all_motifs = nodes_in_motifs_BF | nodes_in_motifs_FFL
        motif_clusters_FFL = get_motifs_clusters(random_subgraph, motifs_FFL, 'ffl')
        motif_clusters_BF = get_motifs_clusters(random_subgraph, motifs_BF, 'bf')
        number_of_cluster_BF = len(motif_clusters_BF)
        number_of_cluster_FFL = len(motif_clusters_FFL)
        cluster_distribution_FFL = Counter([len(x) for x in motif_clusters_FFL])
        cluster_distribution_BF = Counter([len(x) for x in motif_clusters_BF])
<<<<<<< HEAD
    
    # ------ Print Results ---------------------------------- #

=======
>>>>>>> 89e5d90212fe481aeff7c65cc5192a34bc1166f2
        print(f'---------------------Number of Motifs----------------------\n')
        print(f'------------------------ BF Motifs ------------------------')
        print(f'There are a total of {len(motifs_BF_og)} motifs in the original graph and {len(motifs_BF)} motifs in random graph {i} \n')
        print(f'------------------------ FFL Motifs -----------------------')
        print(f'There are a total of {len(motifs_FFL_og)} motifs in the original graph and {len(motifs_FFL)} motifs in random graph {i} \n')
        print(f'--------------------- Number of Nodes ---------------------\n')
        print(f'------------------------ BF Motifs ------------------------')
        print(f'There are a total of {nodes_in_motifs_BF_og} nodes in the original graph and {len(nodes_in_motifs_BF)} nodes  in random graph {i} \n')
        print(f'------------------------ FFL Motifs -----------------------')
        print(f'There are a total of {nodes_in_motifs_FFL_og} nodes in the original graph and {len(nodes_in_motifs_FFL)} nodes  in random graph {i} \n')
        print(f'------------------------ All Motifs -----------------------')
        print(f'There are a total of {nodes_in_all_motifs_og} nodes in the original graph and {len(nodes_in_all_motifs)} nodes  in random graph {i} \n')
        print(f'---------------------Number of Motif Clusters-------------------\n')
        print(f'------------------------ BF Motifs ------------------------')
        print(f'There are a total of {number_of_cluster_BF_og} motifs in the original graph and {number_of_cluster_BF} motifs in random graph {i} \n')
        print(f'------------------------ FFL Motifs -----------------------')
        print(f'There are a total of {number_of_cluster_FFL_og} motifs in the original graph and {number_of_cluster_FFL} motifs in random graph {i} \n')
        print(f'--------------------- Cluster Distribution ---------------------\n')
        print(f'------------------------ BF Motifs ------------------------')
        print(f'The distribution of clusters of motif type BF in the original graph is: \n {cluster_distribution_BF_og} \n')
        print(f'The distribution of clusters of motif type BF in the random graph {i} is: \n {cluster_distribution_BF} \n')
        print(f'------------------------ FFL Motifs ------------------------')
        print(f'The distribution of clusters of motif type BF in the original graph is: \n {cluster_distribution_FFL_og} \n')
        print(f'The distribution of clusters of motif type BF in the random graph {i} is: \n {cluster_distribution_FFL_og} \n')
<<<<<<< HEAD

=======
>>>>>>> 89e5d90212fe481aeff7c65cc5192a34bc1166f2
    # ----------------- END OF FUNCTION --------------------- #

if __name__ == "__main__":

    # ------- IMPLEMENT HERE THE MAIN FOR THIS SESSION ------- #
    import time
    start_time = time.time()
    genome = SeqIO.read('dataset/sequence.gb' , 'genbank')
    G_no = TF_RISet_parse('dataset/TF-RISet.tsv', 'dataset/TFSet.tsv', False, 100, genome, True)
    #G_so = TF_RISet_parse('dataset/TF-RISet.tsv', 'dataset/TFSet.tsv', True, 100, genome,True)
    #G1=nx.read_graphml('Ecoli_TRN.graphml')
    #G2=nx.read_graphml('Ecoli_operon_TRN.graphml')
    compare_with_random_graphs(G_no, 3)

    ...

    print("--- %s seconds ---" % (time.time() - start_time))
    # ------------------- END OF MAIN ------------------------ #

